DROP TABLE IF EXISTS Products CASCADE;

CREATE TABLE Products (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  product_name VARCHAR(255) NULL DEFAULT NULL,
  slogan VARCHAR(255) NULL DEFAULT NULL,
  product_description TEXT NULL DEFAULT NULL,
  category_id VARCHAR(255) NULL DEFAULT NULL,
  default_price INTEGER NULL DEFAULT NULL
);


DROP TABLE IF EXISTS Styles CASCADE;

CREATE TABLE Styles (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  product_id INTEGER REFERENCES Products(id),
  style_name VARCHAR(1024) NULL DEFAULT NULL,
  sale_price VARCHAR(1024) NULL DEFAULT NULL,
  original_price VARCHAR(1024) NULL DEFAULT NULL,
  default_style BOOLEAN
);


DROP TABLE IF EXISTS Skus CASCADE;

CREATE TABLE Skus (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  styles_id INTEGER REFERENCES Styles(id),
  size VARCHAR(255) NULL DEFAULT NULL,
  quantity INTEGER NULL DEFAULT NULL
);



DROP TABLE IF EXISTS Features CASCADE;

CREATE TABLE Features (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  product_id INTEGER REFERENCES Products(id),
  feature VARCHAR(255) NULL DEFAULT NULL,
  feature_value VARCHAR(255) NULL DEFAULT NULL
);


DROP TABLE IF EXISTS Photos CASCADE;

CREATE TABLE Photos (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  styles_id INTEGER REFERENCES Styles(id),
  photo_url TEXT NULL DEFAULT NULL,
  thumbnail_url TEXT NULL DEFAULT NULL
);


DROP TABLE IF EXISTS Related CASCADE;

CREATE TABLE Related (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  current_product_id INTEGER REFERENCES Products(id),
  related_product_id INTEGER REFERENCES Products(id)
);


CREATE INDEX id_idx ON Products (id);
CREATE INDEX id2_idx ON Styles (id);
CREATE INDEX product_id_idx ON Styles (product_id);
CREATE INDEX photos_id_idx ON PHOTOS (styles_id);
CREATE INDEX current_product_id_idx ON Related (current_product_id);
CREATE INDEX skus_id_idx ON Skus (styles_id);
CREATE INDEX features_product_idx ON Features (product_id);